server.port: ${PORT:8085}

spring:
  application.name: ichiro-walks
  profiles.active: ${PROFILE:prod}
  config.import: optional:file:.env[.properties] # enable scanning of .env file

app.time-zone: ${TIMEZONE:UTC+2}

---
spring:
  config.activate.on-profile: dev
  h2.console.enabled: true
  jpa:
    defer-datasource-initialization: true
    show-sql: false
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS MY_SCHEMA\;
    username: sa
    password:

vaadin.productionMode: false
---
spring:
  config.activate.on-profile: prod
  datasource:
    url: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
    username: postgres.rsuhstqfoaoabfzgezxr
    password: ${DB_PASSWORD}

vaadin.productionMode: true
